### ISSUE TITLE
当数据为0时，左滑加载异常，header位置异常

### ISSUE THREAD

**Issue by H2OB** [dangercheng/CollectionViewSideRefresh#3]

**Comment by H2OB** [comment]
DefaultViewController.m文件33行加一句

self.collectionView.alwaysBounceHorizontal = YES;

73行
- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section {
    return 0;
}

即可看见异常

**Comment by dangercheng** [comment]
已修复，感谢反馈！
commit f63ae4f832e7df071cf80ee2e3b1131a48896345
