### ISSUE TITLE
项目在iOS 9 和iOS 10 上会有过度释放引起的crash

### ISSUE THREAD

**Issue by shaoyilong** [dangercheng/CollectionViewSideRefresh#6]
在iOS 9 和 iOS 10 上， 进入列表页，滑动加载新数据后，返回上层页面，crash
初步查看是由于过度释放引起，具体原因还望作者查看下，谢谢

**Comment by chaifuwei1994** [comment]
使用这个第三方的时候，有崩溃的问题。原因涉及到观察模式，在 SideRefreshEmptyFooter.m文件中，修改代码后，不再崩溃 
- (void)dealloc {
    [self.collectionView removeObserver:self.collectionView forKeyPath:@"contentSize"];
}

**Comment by dangercheng** [comment]
@shaoyilong 
感谢反馈，最新的release 1.2已解决.
