### ISSUE TITLE
头部刷新的控件

### ISSUE THREAD

**Issue by todayismancheng** [dangercheng/CollectionViewSideRefresh#7]
头部刷新时候状态label到处乱蹦 不隐藏

**Comment by dangercheng** [comment]
@todayismancheng 
什么情况下回乱蹦不隐藏？可以给我Demo吗？

**Comment by todayismancheng** [comment]
> @todayismancheng
> 什么情况下回乱蹦不隐藏？可以给我Demo吗？

乱蹦的情况解决了。那个是我的collctionVIew设置了pagingEnabled. 现在有个新的问题是底部的刷新完不隐藏，不弹回去，一直就在外面显示

**Comment by dangercheng** [comment]
> 乱蹦的情况解决了。那个是我的collctionVIew设置了pagingEnabled. 现在有个新的问题是底部的刷新完不隐藏，不弹回去，一直就在外面显示

@todayismancheng 还是希望发送你的demo给我看看，dangercheng@qq.com, 期望收到你的邮件。

**Comment by todayismancheng** [comment]
> > 乱蹦的情况解决了。那个是我的collctionVIew设置了pagingEnabled. 现在有个新的问题是底部的刷新完不隐藏，不弹回去，一直就在外面显示
> 
> @todayismancheng 还是希望发送你的demo给我看看，[dangercheng@qq.com](mailto:dangercheng@qq.com), 期望收到你的邮件。

应该是这样。加载更多的时候，返回无数据,而且没有设置底部showEmptyFooter。底部刷新就不会隐藏。 无数据设置showEmptyFooter  就会自动回弹。

**Comment by todayismancheng** [comment]
在cell宽度小于collectionView的宽度 ，只显示一个cell的情况下，显示没有更多数据，刷新完showEmptyFooter 也不会自动隐藏。

**Comment by dangercheng** [comment]
> 在cell宽度小于collectionView的宽度 ，只显示一个cell的情况下，显示没有更多数据，刷新完showEmptyFooter 也不会自动隐藏。

@todayismancheng 下图就是你想要的效果吧？

![0f6a415097b9cbc48de69ca8f5e2af3c](https://user-images.githubusercontent.com/5669786/51291637-cd894580-1a42-11e9-8e5f-fe74df9a87a9.png)

**Comment by dangercheng** [comment]
release 1.3
