### ISSUE TITLE
右滑加载更多，多次右滑刷新collectionview，将会出现footer位置错误

### ISSUE THREAD

**Issue by LongJiang90** [dangercheng/CollectionViewSideRefresh#9]
![ezgif-4-00a582577d79](https://user-images.githubusercontent.com/9586684/52931467-6e8f5700-3387-11e9-9796-b95fa17480bd.gif)
网络请求获取数据后
`
if ('左滑还是右滑') {     [strongSelf.timeCollectionView.sideRefreshHeader endLoading];
        }else{
            [strongSelf.timeCollectionView.sideRefreshFooter endLoading];
        }
`
组装数据，刷新collectionView

**Comment by dangercheng** [comment]
感谢反馈，solved by release 1.4

**Comment by dangercheng** [comment]
@LongJiangSB  感谢反馈，solved by release 1.4

**Comment by LongJiang90** [comment]
感谢大佬的快速修改！
